name: Health Check

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to check'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging
  schedule:
    # Run health check daily at 12:00 PM EST (5:00 PM UTC)
    - cron: '0 17 * * *'

jobs:
  health-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Health Check via SSH
      run: |
        echo "🏥 Running Health Check for ${{ inputs.environment || 'production' }}"
        echo "================================================"
        
        # Note: This assumes you have SSH access to your deployment server
        # You would need to set up SSH keys and server details in secrets
        
        ENVIRONMENT="${{ inputs.environment || 'production' }}"
        CONTAINER_NAME="birthday_bot_${ENVIRONMENT}"
        
        echo "🔍 Checking container status..."
        
        # Mock SSH command - replace with actual SSH to your server
        # ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
        
        # For demonstration, showing what commands would be run:
        echo "Commands that would be executed on deployment server:"
        echo "  docker ps --filter name=${CONTAINER_NAME}"
        echo "  docker inspect ${CONTAINER_NAME} --format='{{.State.Health.Status}}'"
        echo "  docker exec ${CONTAINER_NAME} node scripts/health-check.js"
        echo "  docker logs ${CONTAINER_NAME} --tail 10"
        
        # EOF
        
        echo "✅ Health check workflow completed"
        echo "💡 To enable this workflow, configure:"
        echo "   - SSH access to your deployment server"
        echo "   - DEPLOY_USER and DEPLOY_HOST secrets"
        echo "   - SSH keys for authentication"

  notify-on-failure:
    runs-on: ubuntu-latest
    needs: health-check
    if: failure()
    
    steps:
    - name: Notify on health check failure
      run: |
        echo "❌ Health check failed for ${{ inputs.environment || 'production' }}"
        echo "🚨 This would trigger notifications in a real setup:"
        echo "   - Discord webhook"
        echo "   - Email alerts" 
        echo "   - Slack notifications"
        echo ""
        echo "💡 Configure notification secrets to enable alerts" 